name: "Testing"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ["1.14", "1.15", "1.16", "1.17", "1.18", "1.19"]
    name: GO ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: "Setup dependencies"
        run: |
          go mod download
      - name: "Test"
        run: |
          go test -v ./...
